name: doangiuaki_ppptpmhdt
description: A new Flutter project.

# Ngăn việc vô tình publish lên pub.dev
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Yêu cầu phiên bản Dart 3.0.0 trở lên

#
# === PHẦN DEPENDENCIES ===
#
dependencies:
  flutter:
    sdk: flutter

  # Mặc định của Flutter
  cupertino_icons: ^1.0.2

  # 1. Gọi API
  http: ^1.1.0

  # 2. Quản lý trạng thái
  provider: ^6.0.5

  # 3. Lưu trữ local
  shared_preferences: ^2.2.2

  # 4. Giải mã JWT
  jwt_decode: ^0.3.1

  # 5. Tạo mã QR (cho Admin)
  qr_flutter: ^4.1.0

  # 6. Quét mã QR (cho Student)
  mobile_scanner: ^5.1.2

  # 7. Định dạng ngày tháng
  intl: ^0.19.0

  device_info_plus: ^10.1.0
  path_provider: ^2.1.0
#
# === PHẦN DEV DEPENDENCIES ===
#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# Cấu hình chung của Flutter
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
